Create Server
Dabblr/Concurrent-Document-Editor pull request #2
Opened 2018-11-11 05:43 UTC by kulvirs

Apologies for the large amount of code in this PR! 
I got a bit carried away and decided to actually implement the algorithm for how the server performs updates. I'll try to keep things more modular next time and not bundle so much stuff into one PR.  
Please let me know what suggestions/comments you have.

### Overview
This PR introduces three new packages:
* `objects`
  * contains the JSON objects `File`, `Change`, and `Revision` which are used to communicate information in the requests/responses between the server and client
* `server`
  * contains the server API which has three endpoints for creating files, getting file content, and posting updates to files
  * also contains logic to apply updates on top of previous revisions
* `database`
  * contains an interface which defines all the functions the server needs to interact with the database
  * contains a mock database which implements all the interface functions for unit testing
  * this will eventually contain a file that actually implements the database functions once @NikitaShymberg is done with his database portion

### Checklist:
#### Single User Use Case: 
- [x] create a document with an `HTTP POST` request
 - [x] retrieve the latest version of a document with an `HTTP GET` request
 - [x] send updates for a specific document with an `HTTP POST` request
- [x] confirm that the changes took effect by repeating the first step

#### Multi User Use Case:
- [x] retrieve the latest version of a document **R1** with an `HTTP GET` request
- [x] send an update **U1** with an `HTTP POST` request, identifying **R1** as the working copy
    - the latest version of the document on the server should now be **R2**
- [x] send another update **U2** with an `HTTP POST` request, *also identifying **R1** as the working copy*
- [ ] confirm that the server applied **U2** on top of **R2**, even though we sent the update while working on **R1**

Note: The last box is not checked because of some issues that I discovered with our current method of applying updates. A new PR will be made when those issues are (hopefully) fixed.

### Running the Tests
#### Unit Tests (Go)
For any of the three packages `objects`, `database`, or `server`, perform the following steps to run the unit tests:
```shell
$ cd <package>
$ go test
```
* *NOTE*: use `-v` option for verbose test output

#### API Tests (Postman)
To test the actual server endpoints, I wrote some test scripts in Postman, they can be found at `server/server_tests.postman_collection.json`

To run these tests perform the following steps:
1. Get [Postman](https://www.getpostman.com/apps)
2. Open a terminal and run the server:
```shell
$ cd server
$ go build
$ server
```
3. Open Postman and click `Import`
4. Import the file `server/server_tests.postman_collection.json`
5. Click the arrow next to the `server_tests` folder and then click `Run`
6. In the window that comes up, click `Run server_tests`

2018-11-11 08:02 UTC, okjuan requested changes
This is really great, you did an awesome job! I'm stoked about where this project is going 😄 

Most of my feedback consists of small suggestions; the only major idea I have is that we collapse the `Change` object with the `Insertion`/`Deletion` operations. Let me know what you think!

The only files I did not take a close look at are `revision.go` and `file.go`. I think @NikitaShymberg 's opinion on those would be useful, since he's working on the database.

2018-11-11 08:02 UTC, okjuan commented on objects/change.go
> +	return false
NIT: We could just return the bool value of the if condition

2018-11-11 08:02 UTC, okjuan commented on server/server.go
> +	router.HandleFunc("/file/{id}", PostUpdates).Methods("POST")
NIT: resource names are typically plural (`files` instead of `file`)

2018-11-11 08:02 UTC, okjuan commented on server/server.go
> +	file.RevisionNumber = 1
Maybe we could get the revision number as a 2nd return value from the call to `database.CreateEmptyFile`? I assume the database would also be setting it to 1, but that way we have a single source of truth.

2018-11-11 08:02 UTC, okjuan commented on server/server.go
> +		log.Printf("GET request to /file/%s contained an invalid file ID.\n", params["id"])
NIT: Might be useful to make this statement log a different message from the one above (for debugging purposes, for example).

2018-11-11 08:02 UTC, okjuan commented on server/server.go
> +		log.Printf("POST request to /file/%s contained an invalid file ID.\n", params["id"])
NIT: Same thing here about having a different log statement, maybe something like:
```suggestion
		log.Printf("Could not retrieve file for given ID: %s.\n", params["id"])
```

2018-11-11 08:02 UTC, okjuan commented on server/server.go
> +	w.WriteHeader(http.StatusOK)
Ahh sorry, I originally thought we could avoid returning the new file here, but [apparently](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) that's the norm. So if you still want to return the file contents in the response body, I'm onboard! 🚢

2018-11-11 08:02 UTC, okjuan commented on server/update.go
> +				return newChange, err
NIT: maybe we could return `nil` instead of `newChange` in the error case.

2018-11-11 08:02 UTC, okjuan commented on server/update.go
> +			newChange.Position = newDel.Pos
A `default` case like the one in `ApplyChange` would be nice :-)

2018-11-11 08:02 UTC, okjuan commented on server/update.go
> +		return fileContent, errors.New("invalid change type")
Might be worth adding the index to all these error messages for debugging!

2018-11-11 08:02 UTC, okjuan commented on objects/change.go
> +}
I think we should consider somehow merging the `Change` and `Insertion`/`Deletion` objects. I think the fact that we need the `ChangeToDel` and `ChangeToIns` indicates that having a separate `Change` object is possibly redundant.

Perhaps the `Change` object can consist of an `Operation`, which would be an interface that both `Insertion` and `Deletion` implement. Alternatively, we could just completely remove the `Change` object and treat all operations through an `Operation` interface.

2018-11-14 00:00 UTC, NikitaShymberg approved these changes

2018-11-14 00:04 UTC, NikitaShymberg commented on objects/change.go
> +}
Agreed - I was picturing it as something as simple as a `nil` Value being a deletion and everything else is an insertion.

2018-11-14 09:14 UTC, jcgallegdup commented
@kulvirs Oh yeah, one more thing! Let's update the path from `github.com/jcgallegdup` to `github.com/Dabblr`? 😄

2018-11-19 07:09 UTC, kulvirs commented on objects/change.go
> +	return false
Changed to return bool value of the if condition.

2018-11-19 07:09 UTC, kulvirs commented on server/server.go
> +	router.HandleFunc("/file/{id}", PostUpdates).Methods("POST")
Changed endpoints to use `files` instead of `file`.

2018-11-19 07:10 UTC, kulvirs commented on server/server.go
> +	file.RevisionNumber = 1
Good catch, changed the function `database.CreateEmptyFile` to return a file id and revision number.

2018-11-19 07:10 UTC, kulvirs commented on server/server.go
> +		log.Printf("GET request to /file/%s contained an invalid file ID.\n", params["id"])
Changed invalid ID log messages to be more descriptive.

2018-11-19 07:10 UTC, kulvirs commented on server/server.go
> +		log.Printf("POST request to /file/%s contained an invalid file ID.\n", params["id"])
Similar to above, changed log messages for invalid id to be more descriptive.

2018-11-19 07:13 UTC, kulvirs commented on server/server.go
> +	w.WriteHeader(http.StatusOK)
Hmm...wait so do you want to change it, bit confused what you're asking. Currently the `PostUpdates` endpoint just returns 200 if the request is successful, and 400 if it is not. No body is returned, I thought we were going to assume that the client would call `GET` after `POST`?   
If it is proper convention to return the content with the `POST` request, I can change it to do that.

2018-11-19 07:13 UTC, kulvirs commented on server/update.go
> +				return newChange, err
I wanted to do this too but you can't use a `nil` value for a struct. So we're kind of stuck with this.

2018-11-19 07:14 UTC, kulvirs commented on server/update.go
> +			newChange.Position = newDel.Pos
Added a default case.

2018-11-19 07:14 UTC, kulvirs commented on server/update.go
> +		return fileContent, errors.New("invalid change type")
Added index to error messages.

2018-11-19 07:15 UTC, kulvirs commented on objects/change.go
> +}
As per our discussion last Thursday, we are going to leave this as it is for now. I'm going to create an issue for it so we can remember to come back to it if we figure out a clean way to do this.

2018-11-19 07:16 UTC, kulvirs commented
Updated path from `github.com/jcgallegdup` to `github.com/Dabblr`. Note that you may have to change the name of that folder manually in your own local repo for the imports to work.

2018-11-19 07:35 UTC, okjuan approved these changes
As long as the tests still pass, this looks great to me!

2018-11-19 07:41 UTC, merged